project_name: x509

before:
  hooks:
  - go mod tidy

gomod:
  proxy: true

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.Version={{.Version}} -X main.Revision={{.Commit}}

brews:
- homepage: https://github.com/jamescun/x509
  description: A modern swiss army knife for SSL/TLS certificates.
  license: MIT
  folder: Formula
  commit_author:
    name: James Cunningham
    email: git@jamescun.com
  repository:
    owner: jamescun
    name: homebrew-formulas
    token: "{{ .Env.GITHUB_TOKEN }}"
